### ISSUE TITLE
Device usage enhancement

### ISSUE THREAD

**Issue by rajeshj93** [shamanec/GADS#107]
Hi Gads,
GADS is really useful for making the test device in effective way. I would like to suggest a use case for device usage. Please check the feasibility for implementation

Use Case 1 :
If the device is occupied manually, while running the automation script with same device should throw "no free device to run" or "the selected device is occipied. Please release it before running the script"

Use Case 2 :
If the device is take for automation run, then we should show device as "In use" in the GADS Ui. Since it is showing as use, there is a possibility where the other user can take a control and it leads to our automation script failure.

Use Case 3 : 
If user wants to debug the automation test run, then we should add a "Debug" option next to "In Use " option so user can go through the debug option to see the run

Use Case 4 : 
User name needs to show next to IN USE option to know who is using the device

**Comment by yunki-cmd** [comment]
Hi, I’m glad to hear that GAds is improving every day. It’s a very useful tool for test automation. However, I have a question: in the latest 1.4 release, while automating, the devices get locked and it’s no longer possible to see live executions on the device. I believe that monitoring executions is a very interesting feature. Do you know if it will be implemented in future releases?

**Comment by shamanec** [comment]
They are locking only if you are using the experimental Appium grid, does it actually work?! :D I know about this, though, and its planned to allow opening a device that is currently running automation via some popup for confirmation - so yes, it will be implemented, I was just too lazy to do it in 1.4. I am currently reworking the way devices are registered to allow naming and give more control in the hands of the user instead of doing hotfixes if some device data does not update automatically via the provider. I think I might implement what you are asking for in the same version :)

**Comment by shamanec** [comment]
v2.0.0 is released @rajeshj93 
* Device that is currently in remote control will not be picked up for automation - only when using custom Appium grid
* Device currently running automation cannot be accessed - only when using custom Appium grid
* Use case 3 is not covered for now(check above)
* If device is remotely controlled the UI shows who is using it
