### ISSUE TITLE
black screen on android devices

### ISSUE THREAD

**Issue by brestrepov** [shamanec/GADS#85]
hello, I have successfully configured the project on a mac, when I enter an android device the screen image looks black but if I do any action on the black screen is reflected in the cell phone.
Do you have any idea why the black image is seen and how to fix it?
<img width="741" alt="image" src="https://github.com/shamanec/GADS/assets/96146760/c926b114-22d9-4fa6-93e7-f544a6c18231">

**Comment by shamanec** [comment]
Is the device by any chance running on Android 14? Because Google introduced some changes in the APIs I am using to create the video stream and I havent got around to fixing it yet :( If it's lower than 14 then maybe something is wrong with the GADS-stream setup on the device. You can disconnect the device from the host, open Settings>Apps on the phone and do Force stop on the GADS-stream app. Then manually tap on the GADS-stream icon, you should see a popup asking for recording permissions, allow them, press the Home button and in the device notification bar you should see something like `GADS-stream is recording this device screen`. Then reconnect the device to the host and wait for it to become available and try again :)

**Comment by brestrepov** [comment]
I followed the steps you mentioned and it worked, I am testing on an android 13 device, thanks for your help
<img width="708" alt="image" src="https://github.com/shamanec/GADS/assets/96146760/b9d4759b-41f3-4542-b645-817736b03fb1">

**Comment by shamanec** [comment]
You got it! In theory setup of the stream should happen automatically but sometimes it fails with no obvious reason and I am not sure why :( I got a lot of improvements done but they are still on develop and I am not sure when they'll reach main. Nevertheless if you encounter other issues let me know :)

**Comment by shamanec** [comment]
That was handled

**Comment by shamanec** [comment]
Actually that was not handled - the problem is with the stream app itself - if the device is locked then the activity and stream do not start properly.. 😅 as long as your device is unlocked it should reliably start
